// Assembles the generated A1 lesson JSON files (content-src/a1/*.json) into a single SQL
// migration: supabase/migrations/0009_a1_rich_content.sql
// Run with: node supabase/content-src/assemble-a1.mjs

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = join(__dirname, "a1");
const OUT_FILE = join(__dirname, "..", "migrations", "0009_a1_rich_content.sql");

// Fixed topic order → stable sort_order + deterministic lesson UUIDs.
const TOPIC_ORDER = [
  "kennismaken",
  "familie",
  "getallen-tijd",
  "eten-drinken",
  "boodschappen",
  "wonen",
  "vervoer",
  "dokter",
];
const SKILL_ORDER = ["lezen", "luisteren", "schrijven", "spreken"];

function sqlStr(value) {
  if (value === null || value === undefined) return "null";
  return "'" + String(value).replace(/'/g, "''") + "'";
}

function sqlJson(obj) {
  return "'" + JSON.stringify(obj).replace(/'/g, "''") + "'::jsonb";
}

function lessonUuid(index) {
  const hex = String(index + 1).padStart(12, "0");
  return `a1c00000-0000-4000-8000-${hex}`;
}

const files = readdirSync(SRC_DIR).filter((f) => f.endsWith(".json"));
const lessons = [];
const skipped = [];

for (const file of files) {
  try {
    const data = JSON.parse(readFileSync(join(SRC_DIR, file), "utf8"));
    if (!data.skill || !data.slug || !data.title || !data.content) {
      skipped.push(`${file} (missing required fields)`);
      continue;
    }
    lessons.push(data);
  } catch (err) {
    skipped.push(`${file} (${err.message})`);
  }
}

// Stable order: by topic, then by skill.
lessons.sort((a, b) => {
  const ta = TOPIC_ORDER.indexOf(a.slug);
  const tb = TOPIC_ORDER.indexOf(b.slug);
  if (ta !== tb) return ta - tb;
  return SKILL_ORDER.indexOf(a.skill) - SKILL_ORDER.indexOf(b.skill);
});

const parts = [];
parts.push("-- A1 rich lesson content (original, AI-generated). Generated by assemble-a1.mjs.");
parts.push("-- Run after 0008_lesson_rich_content.sql.");
parts.push("");

lessons.forEach((lesson, index) => {
  const id = lessonUuid(index);
  const topicIndex = TOPIC_ORDER.indexOf(lesson.slug);
  const sortOrder = 20 + (topicIndex >= 0 ? topicIndex : index);
  const isFree = lesson.slug === "kennismaken";

  parts.push(`-- ${lesson.skill} — ${lesson.topic}`);
  parts.push(
    `insert into lessons (id, level_code, skill_code, title, description, sort_order, is_free, content) values (`,
  );
  parts.push(`  ${sqlStr(id)}, 'A1', ${sqlStr(lesson.skill)}, ${sqlStr(lesson.title)},`);
  parts.push(`  ${sqlStr(lesson.description ?? null)}, ${sortOrder}, ${isFree}, ${sqlJson(lesson.content)}`);
  parts.push(`);`);

  const exercises = [];

  if (lesson.skill === "lezen" && lesson.readingText) {
    exercises.push({
      type: "reading_text",
      prompt: "Lees de tekst.",
      content: { text: lesson.readingText },
      answer: null,
    });
  }
  if (lesson.skill === "luisteren" && Array.isArray(lesson.dialogue)) {
    exercises.push({
      type: "listening_clip",
      prompt: "Beluister het gesprek.",
      content: { dialogue: lesson.dialogue },
      answer: null,
    });
  }
  if (lesson.skill === "schrijven" && lesson.writing) {
    exercises.push({
      type: "writing_task",
      prompt: "Schrijf de tekst.",
      content: { instructions: lesson.writing.instructions, minWords: lesson.writing.minWords },
      answer: null,
    });
  }
  if (lesson.skill === "spreken" && lesson.speaking) {
    exercises.push({
      type: "speaking_prompt",
      prompt: "Oefen hardop.",
      content: { scenario: lesson.speaking.scenario, expectedPoints: lesson.speaking.expectedPoints },
      answer: null,
    });
  }
  if (Array.isArray(lesson.questions)) {
    for (const q of lesson.questions) {
      exercises.push({
        type: "multiple_choice",
        prompt: "Kies het juiste antwoord.",
        content: { question: q.question, options: q.options },
        answer: { correctIndex: q.correctIndex, explanation: q.explanation },
      });
    }
  }

  exercises.forEach((ex, exIndex) => {
    parts.push(
      `insert into exercises (lesson_id, type, prompt, content, correct_answer, sort_order) values (`,
    );
    parts.push(
      `  ${sqlStr(id)}, ${sqlStr(ex.type)}, ${sqlStr(ex.prompt)}, ${sqlJson(ex.content)}, ${
        ex.answer ? sqlJson(ex.answer) : "null"
      }, ${exIndex + 1}`,
    );
    parts.push(`);`);
  });

  parts.push("");
});

writeFileSync(OUT_FILE, parts.join("\n"), "utf8");

console.log(`Assembled ${lessons.length} lessons into ${OUT_FILE}`);
if (skipped.length > 0) {
  console.log(`Skipped ${skipped.length} file(s):`);
  for (const s of skipped) console.log("  - " + s);
}
